add dimens, add item to publish
andrespaez90/ShareCar pull request #1
Opened 2017-05-08 03:49 UTC by AndresUrregoC

2017-05-15 15:12 UTC, andrespaez90 requested changes

2017-05-15 15:12 UTC, andrespaez90 commented on app/src/main/java/sharecar/dev/com/sharecar/ui/bindings/GeneralBinding.java
> +    @BindingAdapter({"format", "text"})
android:text= "@{String.format(@string/Generic_Text, Profile.name)}"

2017-05-15 15:12 UTC, andrespaez90 commented on app/src/main/res/values/colors.xml
> +    <color name="gray_300">#E0E0E0</color>
Nombres más significativos

2017-05-15 15:12 UTC, andrespaez90 commented on app/src/main/res/layout/view_publish.xml
> +        <import type="sharecar.dev.com.sharecar.R"/>
primero los imports antes de las variables

2017-05-22 04:04 UTC, AndresUrregoC commented on app/src/main/res/values/colors.xml
> +    <color name="gray_300">#E0E0E0</color>
Pailas, https://material.io/guidelines/style/color.html

2017-05-22 13:07 UTC, merged